[project]
name = "walmart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "databricks>=0.2",
    "dbt-core>=1.12.0",
    "dbt-postgres>=1.11.0",
    "dotenv>=0.9.9",
    "logging>=0.4.9.6",
    "matplotlib>=3.11.1",
    "mongo>=0.2.0",
    "postgres>=4.0",
    "pyarrow>=25.0.0",
    "pymongo>=4.17.0",
    "pyspark==3.5.5",
    "rich>=15.0.0",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.51",
]
