/*
===============================================================================
Query Name : ABC Product Classification Report
Layer      : Gold
Purpose    : Classify products into A, B, and C categories based on their
             contribution to total sales revenue.

Description:
- Calculates total revenue generated by each product.
- Ranks products by revenue in descending order.
- Computes each product's revenue contribution.
- Calculates cumulative revenue and cumulative revenue percentage.
- Classifies products using ABC analysis:
    • Class A : Top 80% of cumulative revenue
    • Class B : Next 15% of cumulative revenue (80%–95%)
    • Class C : Remaining 5% of cumulative revenue
- Returns an inventory prioritization report for business decision-making.

Business Applications:
- Inventory Management
- Stock Replenishment
- Warehouse Optimization
- Product Portfolio Analysis
- Procurement Planning

Required Output:
    • Product ID
    • Product Name
    • Brand Name
    • Category
    • Total Orders
    • Quantity Sold
    • Total Revenue
    • Revenue Rank
    • Revenue Contribution (%)
    • Cumulative Revenue
    • Cumulative Revenue (%)
    • ABC Category

Sort the report by Total Revenue in descending order.

Source Tables:
    gold.fact_order_items
    gold.dim_products

Author      : Nitin
Created On  : 2026-08-06
===============================================================================
*/

WITH product_base AS (
    SELECT
        p.product_id,
        p.product_name,
        b.brand_name,
        c.category_name,
        COUNT(DISTINCT oi.order_id) AS total_orders,
        SUM(oi.quantity) AS quantity_sold,
        SUM(oi.line_amount) AS total_revenue,
        DENSE_RANK() OVER (
            ORDER BY
                SUM(oi.line_amount) DESC, p.product_id ASC

        ) AS revenue_rank
    FROM gold.fact_order_items AS oi
    INNER JOIN gold.dim_products AS p
        ON oi.product_id = p.product_id
    INNER JOIN gold.dim_brands AS b
        ON p.brand_id = b.brand_id
    INNER JOIN gold.dim_categories AS c
        ON p.category_id = c.category_id
    GROUP BY
        p.product_id, p.product_name,
        b.brand_name, c.category_name
),

grand_total AS (
    SELECT SUM(total_revenue) AS grand_revenue
    FROM product_base
),

analysis_base AS (
    SELECT
        pb.product_id,
        pb.product_name,
        pb.brand_name,
        pb.category_name,
        pb.total_orders,
        pb.quantity_sold,
        pb.total_revenue,
        pb.revenue_rank,
        ROUND(
            pb.total_revenue * 100.0
            / gt.grand_revenue,
            2
        ) AS revenue_pct,
        SUM(pb.total_revenue) OVER (
            ORDER BY
                pb.total_revenue DESC,
                pb.product_id ASC
            ROWS BETWEEN UNBOUNDED PRECEDING
            AND CURRENT ROW
        ) AS cumulative_revenue,
        ROUND(
            SUM(pb.total_revenue) OVER (
                ORDER BY
                    pb.total_revenue DESC,
                    pb.product_id ASC
                ROWS BETWEEN UNBOUNDED PRECEDING
                AND CURRENT ROW
            ) * 100.0
            / gt.grand_revenue,
            2
        ) AS cumulative_pct
    FROM product_base AS pb
    CROSS JOIN grand_total AS gt
)

SELECT
    product_id,
    product_name,
    brand_name,
    category_name,
    total_orders,
    quantity_sold,
    total_revenue,
    revenue_rank,
    revenue_pct,
    cumulative_pct,
    ROUND(cumulative_revenue, 2) AS cumulative_revenue,
    CASE
        WHEN cumulative_pct <= 80 THEN 'A'
        WHEN cumulative_pct <= 95 THEN 'B'
        ELSE 'C'
    END AS abc_category
FROM analysis_base
ORDER BY
    total_revenue DESC,
    product_id ASC;
